// Single entry point the UI imports for all commerce data.
// Automatically uses Shopify once SHOPIFY_STORE_DOMAIN /
// SHOPIFY_STOREFRONT_ACCESS_TOKEN are set; falls back to mock data
// otherwise. This is the ONLY file that should know both sources exist —
// every exported function here switches consistently, so nothing stays
// silently pinned to mock data once Shopify is configured.

import { isShopifyConfigured } from "@/lib/data/shopify/client";
import * as shopifyProducts from "@/lib/data/shopify/products";
import * as shopifyCart from "@/lib/data/shopify/cart";
import * as shopifyReviews from "@/lib/data/shopify/reviews";
import * as mockProductsApi from "@/lib/data/mock/products";
import * as mockCartApi from "@/lib/data/mock/cart";
import * as mockCollectionsApi from "@/lib/data/mock/collections";
import * as mockReviewsApi from "@/lib/data/mock/reviews";
import type { Product, Collection } from "@/lib/types/product";

export const usingLiveShopify = isShopifyConfigured;

// ---- Products ----

export const getProductByHandle = isShopifyConfigured
  ? shopifyProducts.getProductByHandle
  : mockProductsApi.getProductByHandle;

export const getAllProducts = isShopifyConfigured ? shopifyProducts.getAllProducts : mockProductsApi.getAllProducts;

// Card-weight product list for grids — mock data is already tiny
// in-memory objects, so there's no separate lightweight mock source to
// switch to; only the live Shopify path benefits from the smaller query.
export const getAllProductCards = isShopifyConfigured ? shopifyProducts.getAllProductCards : mockProductsApi.getAllProducts;

// "all" is a special pseudo-collection meaning "every product" — it is
// NOT a real Shopify collection. Shopify has no built-in collection with
// handle "all" (the old /collections/all URL some themes show is
// generated by the theme, not backed by an actual collection object),
// so querying Shopify for one always returns nothing. Handle it directly
// from the product list instead; only real, merchant-created collection
// handles go through an actual Shopify collection lookup.
export async function getCollectionByHandle(handle: string): Promise<Collection | undefined> {
  if (handle === "all") {
    const products = await getAllProductCards(100);
    return { id: "all-products", handle: "all", title: "All products", products };
  }

  return isShopifyConfigured ? shopifyProducts.getCollectionByHandle(handle) : mockCollectionsApi.getCollectionByHandle(handle);
}

// Related products are derived generically from whichever product list
// the active data source returns — so this automatically uses real
// Shopify products once configured, without a separate Shopify-specific
// implementation to keep in sync. Uses the card-weight list since only
// ProductCard ever renders these.
export async function getRelatedProducts(excludeHandle: string, limit = 3): Promise<Product[]> {
  const all = await getAllProductCards();
  return all.filter((p) => p.handle !== excludeHandle).slice(0, limit);
}

// Sitemap-only: handle + real last-modified date where known. Mock mode
// has no real "updated" timestamp, so it's simply omitted (never
// fabricated) — see sitemap.ts for how a missing date is handled.
export const getAllProductHandles: () => Promise<{ handle: string; updatedAt?: string }[]> = isShopifyConfigured
  ? shopifyProducts.getAllProductHandles
  : async () => mockProductsApi.mockProducts.map((p) => ({ handle: p.handle }));

// The homepage's hero/featured product is simply the first product the
// active data source returns — no manually configured handle to keep in
// sync. This is intentionally store-agnostic: adding, removing, or
// reordering products in Shopify changes the homepage automatically.
export async function getHeroProduct(): Promise<Product | undefined> {
  const all = await getAllProducts();
  return all[0];
}

// ---- Reviews ----
// Reviews remain empty until a legitimate provider is connected.
// Production never falls back to fabricated customer feedback.

export const getReviews = isShopifyConfigured ? shopifyReviews.getReviews : mockReviewsApi.getReviews;

// ---- Cart ----

export const createCart = isShopifyConfigured ? shopifyCart.createCart : mockCartApi.createCart;
export const addCartLine = isShopifyConfigured ? shopifyCart.addCartLine : mockCartApi.addCartLine;
export const updateCartLine = isShopifyConfigured ? shopifyCart.updateCartLine : mockCartApi.updateCartLine;
export const removeCartLine = isShopifyConfigured ? shopifyCart.removeCartLine : mockCartApi.removeCartLine;
export const getCart = isShopifyConfigured ? shopifyCart.getCart : mockCartApi.getCart;
